### ISSUE TITLE
Fail to download the pretrained model 

### ISSUE THREAD

**Issue by jingtaozhan** [Albert-Ma/PROP#1]
Hi, this is a great work! However, I failed to download the pretrained model. The given link points to an empty folder. Is the pretrained model available yet?

**Comment by Albert-Ma** [comment]
Hi, I released the [prop_step400k base](https://drive.google.com/file/d/1aw0s1UK8PvZCI9R8hA9b7kxoN0x35kRr/view?usp=sharing)  model which we got first place on the [MSMARCO Document Ranking Leaderboard](https://microsoft.github.io/MSMARCO-Document-Ranking-Submissions/leaderboard/). Note that the `prop_step400k base` is different from the model we used in our WSDM 2021 paper and these models will be available soon. Too busy now.

**Comment by jingtaozhan** [comment]
Great! Congratulations!
I assume you use PROP for second-stage ranking. Which model did you use for first-stage ranking? I'm currently working on first-stage retrieval and it performs very well on MS MARCO document ranking task. I think maybe we can work together and further improve the document retrieval performance.

**Comment by Albert-Ma** [comment]
Sorry for the delay. 
Yeah, PROP is designed for reranking. Currently, for the result we submitted to the leaderboard, we use BM25 to retrieve top100 doc2query augmented docs. We are digging into dense presentations too and I am glad to cooperate with you in a proper way. Maybe we can talk about this via email. Here is my email: maxinyu17g@ict.ac.cn
