### ISSUE TITLE
Question about your mlm mask

### ISSUE THREAD

**Issue by zyznull** [Albert-Ma/PROP#10]
I notice that in the pretrainng process, the mlm words do not be masked? Is this a bug of this version code?

**Comment by Albert-Ma** [comment]
No, we preprocess the data including masking words and constructing the ROP task before the pretraining. See [this]( https://github.com/Albert-Ma/PROP/blob/main/prop_pretraining/multiprocessing_generate_pairwise_instances.py#L86)
