### ISSUE TITLE
数据预处理脚本问题

### ISSUE THREAD

**Issue by tangjiawei777** [Albert-Ma/PROP#13]
当执行./scripts/process.sh命令时

INPUT_FILE=./data/wiki_info
Bert_MODEL_DIR=../bert-base-uncased-py（PROP目录下没有bert-base-uncased文件啊，这是怎么回事呀？）

python -m prop.preprocessing_data \
    --corpus_name wikipedia \
    --data_file ${INPUT_FILE}/wiki_info/wiki_toy.data \ （q1:是不是多写了一个wiki_info，q2:wiki_toy.data难道不是我们的输入数据么，然后根据这个输入数据生成相应的json文件）
    --bert_model ${Bert_MODEL_DIR} \
    --do_lower_case \
    --output_dir ${INPUT_FILE}/wiki_info/

**Comment by Albert-Ma** [comment]
1. bert-base-uncased 文件太大 不适合放在github上，可以自己下载 
2. q1:wiki_info只是一个目录 可以没有 q2:wiki_toy.data 是预训练的语料库
