### ISSUE TITLE
发布的模型文件可以直接使用huggingface transformers来Load吗？

### ISSUE THREAD

**Issue by zhengyima** [Albert-Ma/PROP#2]
谢谢

**Comment by Albert-Ma** [comment]
可以的，你把模型文件名字命名成`pytorch_model.bin`，在下载`config.json` 和 `vocab.txt`放在同一个目录下，load模型的时候调用`from_pretrained(MODEL_PATH)`就可以了

具体可以看这里[link](https://github.com/huggingface/transformers/blob/master/src/transformers/file_utils.py#L195),  huggingface transformers 对一些模型的名字有一些预定义

**Comment by zhengyima** [comment]
好的，已经实验成功了。

**Comment by MooreAndMoore** [comment]
xc

**Comment by MooreAndMoore** [comment]
请问您是用BertModel这个类的吗？
